spring.application.name=pmajay-backend

server.port=${PORT:8083}

# ===============================
# MYSQL DATABASE
# ===============================

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://bjh3xejfpmuusfltjeb4-mysql.services.clever-cloud.com:3306/bjh3xejfpmuusfltjeb4}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:u6n98au9alayrvfk}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:9M7y5PlbuO21EhQgTk8u}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# REMOVE if present
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# HIKARI CONNECTION POOL
# ===============================

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.connection-timeout=60000

# ===============================
# JWT
# ===============================

jwt.secret=${JWT_SECRET:pmajay-super-secret-key-2025-do-not-share}
jwt.expiration=86400000

# ===============================
# FILE UPLOAD
# ===============================

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ===============================
# LOGGING
# ===============================

logging.level.org.springframework.security=ERROR
logging.level.org.hibernate.SQL=ERROR