spring.application.name=pmajay-backend

server.port=${PORT:8083}

# ===============================
# MYSQL DATABASE
# ===============================

spring.datasource.url=jdbc:mysql://bjh3xejfpmuusfltjeb4-mysql.services.clever-cloud.com:3306/bjh3xejfpmuusfltjeb4

spring.datasource.username=u6n98au9alayrvfk

spring.datasource.password=9M7y5PlbuO21EhQgTk8u

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ===============================
# JWT
# ===============================

jwt.secret=pmajay_super_secret_key_2026
jwt.expiration=86400000

# ===============================
# FILE UPLOAD
# ===============================

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ===============================
# LOGGING
# ===============================

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG